### ISSUE TITLE
Make Meme software "cheat sheet"

### ISSUE THREAD

**Issue by ksiewert** [greenelab/GCB535#83]
We think it would be super useful to have short  bullet point descriptions of what each software (Meme, Jasper, Opossum, TomTom) does and what you use them for. This info is all in the assignments, but it's hard for the students to wrap their heads around what all of them are doing at once, and so they lose sight of the big picture.

**Comment by bvoight** [comment]
It turns out that 
http://meme-suite.org/ 

already essentially solved this problem. They have a nice graphic which describes workflows, and each tool is listed with broad category of what each tool does, and a nice mouse-over feature when you point to the tool to describe what it does. 

So I'm going to add a little tidbit to the prelab motif-I which points to this website link, then some prelab questions to verify that they have looked at this website
